In [5]:
import random
import numpy as np

In [11]:
arr = np.zeros((8,8))

In [12]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
def placeQueen(arr):
    rows = random.randint(0, 7)
    cols = random.randint(0, 7)
    arr[rows][cols] = 1

In [19]:
placeQueen(arr)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
def checkConflict(arr):
    queens = []
    for i in range(0,7):
        for j in range(0,7):
            if arr[i][j] == 1:
               queens.append((i,j))
    
    conflicts = 0
    
    for i in range(len(queens)):
        for j in range(i+1, len(queens)):
            queen1_row, queen1_col = queens[i]
            queen2_row, queen2_col = queens[j]
            
            if queen1_row == queen2_row:
                conflicts += 1
            
            elif queen1_col == queen2_col:
                conflicts += 1
            
            elif abs(queen1_row - queen2_row) == abs(queen1_col - queen2_col):
                conflicts += 1

    return conflicts